In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\santo\OneDrive\Desktop\Real estate intelligence\data\raw\real_estate_market_in_India.csv")

In [4]:
df.head()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",22.592200,88.484911,60.5

In [5]:
df.shape

(29451, 12)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   POSTED_BY              29451 non-null  str
 1   UNDER_CONSTRUCTION     29451 non-null  int64
 2   RERA                   29451 non-null  int64
 3   BHK_NO.                29451 non-null  int64
 4   BHK_OR_RK              29451 non-null  str
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64
 7   RESALE                 29451 non-null  int64
 8   ADDRESS                29451 non-null  str
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int64(5), str(3)
memory usage: 3.5 MB

In [7]:
df.describe()

,UNDER_CONSTRUCTION,RERA,BHK_NO.,SQUARE_FT,READY_TO_MOVE,RESALE,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
count,29451.000000,29451.000000,29451.000000,2.945100e+04,29451.000000,29451.000000,29451.000000,29451.000000,29451.000000
mean,0.179756,0.317918,2.392279,1.980217e+04,0.820244,0.929578,21.300255,76.837695,142.898746
std,0.383991,0.465675,0.879091,1.901335e+06,0.383991,0.255861,6.205306,10.557747,656.880713
min,0.000000,0.000000,1.000000,3.000000e+00,0.000000,0.000000,-37.713008,-121.761248,0.250000
25%,0.000000,0.000000,2.000000,9.000211e+02,1.000000,1.000000,18.452663,73.798100,38.000000
50%,0.000000,0.000000,2.000000,1.175057e+03,1.000000,1.000000,20.750000,77.324137,62.000000
75%,0.000000,1.000000,3.000000,1.550688e+03,1.000000,1.000000,26.900926,77.828740,100.000000
max,1.000000,1.000000,20.000000,2.545455e+08,1.000000,1.000000,59.912884,152.962676,30000.000000

In [8]:
df.describe

<bound method NDFrame.describe of       POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0         Owner                   0     0        2       BHK  1300.236407
1        Dealer                   0     0        2       BHK  1275.000000
2         Owner                   0     0        2       BHK   933.159722
3         Owner                   0     1        2       BHK   929.921143
4        Dealer                   1     0        2       BHK   999.009247
...         ...                 ...   ...      ...       ...          ...
29446     Owner                   0     0        3       BHK  2500.000000
29447     Owner                   0     0        2       BHK   769.230769
29448    Dealer                   0     0        2       BHK  1022.641509
29449     Owner                   0     0        2       BHK   927.079009
29450    Dealer                   0     1        2       BHK   896.774194

       READY_TO_MOVE  RESALE                            ADDRESS  LONGITUDE  \
0                  1       1              Ksfc Layout,Bangalore  12.969910
1                  1       1          Vishweshwara Nagar,Mysore  12.274538
2                  1       1                   Jigani,Bangalore  12.778033
3                  1       1        Sector-1 Vaishali,Ghaziabad  28.642300
4                  0       1                   New Town,Kolkata  22.592200
...              ...     ...                                ...        ...
29446              1       1               Shamshabad Road,Agra  27.140626
29447              1       1  E3-108, Lake View Recidency,,Vapi  39.945409
29448              1       1                  Ajmer Road,Jaipur  26.928785
29449              1       1             Sholinganallur,Chennai  12.900150
29450              1       1                   Jagatpura,Jaipur  26.832353

        LATITUDE  TARGET(PRICE_IN_LACS)
0      77.597960                   55.0
1      76.644605                   51.0
2      77.632191                   43.0
3      77.344500                   62.5
4      88.484911                   60.5
...          ...                    ...
29446  78.043277                   45.0
29447 -86.150721                   16.0
29448  75.828002                   27.1
29449  80.227910                   67.0
29450  75.841749                   27.8

[29451 rows x 12 columns]>

In [10]:
df.nunique()

POSTED_BY                    3
UNDER_CONSTRUCTION           2
RERA                         2
BHK_NO.                     16
BHK_OR_RK                    2
SQUARE_FT                19561
READY_TO_MOVE                2
RESALE                       2
ADDRESS                   6899
LONGITUDE                 4087
LATITUDE                  4078
TARGET(PRICE_IN_LACS)     1172
dtype: int64

In [11]:
print(df['POSTED_BY'].value_counts())

POSTED_BY
Dealer     18291
Owner      10538
Builder      622
Name: count, dtype: int64

In [12]:
print(df["BHK_OR_RK"].value_counts())

BHK_OR_RK
BHK    29427
RK        24
Name: count, dtype: int64

In [13]:
print(df['BHK_NO.'].value_counts().sort_index())

BHK_NO.
1      3574
2     13324
3     10546
4      1723
5       190
6        52
7        11
8        10
9         3
10        4
11        1
12        3
13        1
15        4
17        1
20        4
Name: count, dtype: int64

In [15]:
print(df["TARGET(PRICE_IN_LACS)"].describe())

count    29451.000000
mean       142.898746
std        656.880713
min          0.250000
25%         38.000000
50%         62.000000
75%        100.000000
max      30000.000000
Name: TARGET(PRICE_IN_LACS), dtype: float64

In [16]:
## Initial Observations
# -Dataset contains approximately 29,451 records
# -Dataset contains 12 columns.
# -Target variables is TARGET(PRICE_IN LACS).
# -Dataset contains 24 RK and 29,427 BHK