In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\santo\OneDrive\Desktop\Real estate intelligence\data\raw\real_estate_market_in_India.csv")

In [4]:
df.head()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",22.592200,88.484911,60.5

In [5]:
df.shape

(29451, 12)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   POSTED_BY              29451 non-null  str
 1   UNDER_CONSTRUCTION     29451 non-null  int64
 2   RERA                   29451 non-null  int64
 3   BHK_NO.                29451 non-null  int64
 4   BHK_OR_RK              29451 non-null  str
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64
 7   RESALE                 29451 non-null  int64
 8   ADDRESS                29451 non-null  str
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int64(5), str(3)
memory usage: 3.5 MB

In [7]:
df.describe()

,UNDER_CONSTRUCTION,RERA,BHK_NO.,SQUARE_FT,READY_TO_MOVE,RESALE,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
count,29451.000000,29451.000000,29451.000000,2.945100e+04,29451.000000,29451.000000,29451.000000,29451.000000,29451.000000
mean,0.179756,0.317918,2.392279,1.980217e+04,0.820244,0.929578,21.300255,76.837695,142.898746
std,0.383991,0.465675,0.879091,1.901335e+06,0.383991,0.255861,6.205306,10.557747,656.880713
min,0.000000,0.000000,1.000000,3.000000e+00,0.000000,0.000000,-37.713008,-121.761248,0.250000
25%,0.000000,0.000000,2.000000,9.000211e+02,1.000000,1.000000,18.452663,73.798100,38.000000
50%,0.000000,0.000000,2.000000,1.175057e+03,1.000000,1.000000,20.750000,77.324137,62.000000
75%,0.000000,1.000000,3.000000,1.550688e+03,1.000000,1.000000,26.900926,77.828740,100.000000
max,1.000000,1.000000,20.000000,2.545455e+08,1.000000,1.000000,59.912884,152.962676,30000.000000

In [8]:
df.describe

<bound method NDFrame.describe of       POSTED_BY  UNDER_CONSTRUCTION  RERA  BHK_NO. BHK_OR_RK    SQUARE_FT  \
0         Owner                   0     0        2       BHK  1300.236407
1        Dealer                   0     0        2       BHK  1275.000000
2         Owner                   0     0        2       BHK   933.159722
3         Owner                   0     1        2       BHK   929.921143
4        Dealer                   1     0        2       BHK   999.009247
...         ...                 ...   ...      ...       ...          ...
29446     Owner                   0     0        3       BHK  2500.000000
29447     Owner                   0     0        2       BHK   769.230769
29448    Dealer                   0     0        2       BHK  1022.641509
29449     Owner                   0     0        2       BHK   927.079009
29450    Dealer                   0     1        2       BHK   896.774194

       READY_TO_MOVE  RESALE                            ADDRESS  LONGITUDE  \
0                  1       1              Ksfc Layout,Bangalore  12.969910
1                  1       1          Vishweshwara Nagar,Mysore  12.274538
2                  1       1                   Jigani,Bangalore  12.778033
3                  1       1        Sector-1 Vaishali,Ghaziabad  28.642300
4                  0       1                   New Town,Kolkata  22.592200
...              ...     ...                                ...        ...
29446              1       1               Shamshabad Road,Agra  27.140626
29447              1       1  E3-108, Lake View Recidency,,Vapi  39.945409
29448              1       1                  Ajmer Road,Jaipur  26.928785
29449              1       1             Sholinganallur,Chennai  12.900150
29450              1       1                   Jagatpura,Jaipur  26.832353

        LATITUDE  TARGET(PRICE_IN_LACS)
0      77.597960                   55.0
1      76.644605                   51.0
2      77.632191                   43.0
3      77.344500                   62.5
4      88.484911                   60.5
...          ...                    ...
29446  78.043277                   45.0
29447 -86.150721                   16.0
29448  75.828002                   27.1
29449  80.227910                   67.0
29450  75.841749                   27.8

[29451 rows x 12 columns]>

In [9]:
df.nunique()

POSTED_BY                    3
UNDER_CONSTRUCTION           2
RERA                         2
BHK_NO.                     16
BHK_OR_RK                    2
SQUARE_FT                19561
READY_TO_MOVE                2
RESALE                       2
ADDRESS                   6899
LONGITUDE                 4087
LATITUDE                  4078
TARGET(PRICE_IN_LACS)     1172
dtype: int64

In [10]:
print(df['POSTED_BY'].value_counts())

POSTED_BY
Dealer     18291
Owner      10538
Builder      622
Name: count, dtype: int64

In [11]:
print(df["BHK_OR_RK"].value_counts())

BHK_OR_RK
BHK    29427
RK        24
Name: count, dtype: int64

In [12]:
print(df['BHK_NO.'].value_counts().sort_index())

BHK_NO.
1      3574
2     13324
3     10546
4      1723
5       190
6        52
7        11
8        10
9         3
10        4
11        1
12        3
13        1
15        4
17        1
20        4
Name: count, dtype: int64

In [13]:
print(df["TARGET(PRICE_IN_LACS)"].describe())

count    29451.000000
mean       142.898746
std        656.880713
min          0.250000
25%         38.000000
50%         62.000000
75%        100.000000
max      30000.000000
Name: TARGET(PRICE_IN_LACS), dtype: float64

In [14]:
## Initial Observations
# -Dataset contains approximately 29,451 records
# -Dataset contains 12 columns.
# -Target variables is TARGET(PRICE_IN LACS).
# -Dataset contains 24 RK and 29,427 BHK

In [15]:

df["TARGET(PRICE_IN_LACS)"].mean()

np.float64(142.89874571321857)

In [16]:
df["TARGET(PRICE_IN_LACS)"].median()

np.float64(62.0)

In [20]:

df["TARGET(PRICE_IN_LACS)"].min()

np.float64(0.25)

In [21]:
df["TARGET(PRICE_IN_LACS)"].max()

np.float64(30000.0)

In [22]:
df.isnull().sum()

POSTED_BY                0
UNDER_CONSTRUCTION       0
RERA                     0
BHK_NO.                  0
BHK_OR_RK                0
SQUARE_FT                0
READY_TO_MOVE            0
RESALE                   0
ADDRESS                  0
LONGITUDE                0
LATITUDE                 0
TARGET(PRICE_IN_LACS)    0
dtype: int64

In [23]:
df.isnull()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,False,False,False,False,False,False,False,False,False,False,False,False
29447,False,False,False,False,False,False,False,False,False,False,False,False
29448,False,False,False,False,False,False,False,False,False,False,False,False
29449,False,False,False,False,False,False,False,False,False,False,False,False
29450,False,False,False,False,False,False,False,False,False,False,False,False

In [24]:
df.duplicated().sum()

np.int64(401)

In [25]:
duplicates = df[df.duplicated()]

In [26]:
duplicates.head()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
1904,Dealer,1,0,3,BHK,1209.628644,0,1,"Salt Lake,Kolkata",22.541110,88.337780,100.0
2351,Dealer,0,0,2,BHK,896.680112,1,1,"Zirakpur,Chandigarh",30.662283,76.822397,28.9
2611,Dealer,0,0,3,BHK,1350.256549,1,1,"Sector 78 Faridabad,Faridabad",28.380160,77.369936,50.0
2618,Dealer,1,0,2,BHK,800.000000,0,1,"Chandapura,Bangalore",12.800090,77.711820,27.0
3211,Owner,0,0,2,BHK,712.105799,1,1,"BataNagar,Kolkata",22.506860,88.223965,35.0

In [27]:
len(duplicates)

401

In [28]:
df = df.drop_duplicates()

In [29]:
df.shape

(29050, 12)

In [30]:
df.dtypes

POSTED_BY                    str
UNDER_CONSTRUCTION         int64
RERA                       int64
BHK_NO.                    int64
BHK_OR_RK                    str
SQUARE_FT                float64
READY_TO_MOVE              int64
RESALE                     int64
ADDRESS                      str
LONGITUDE                float64
LATITUDE                 float64
TARGET(PRICE_IN_LACS)    float64
dtype: object

In [31]:
df["BHK_NO."].value_counts().sort_index()

BHK_NO.
1      3540
2     13164
3     10365
4      1698
5       189
6        52
7        11
8        10
9         3
10        4
11        1
12        3
13        1
15        4
17        1
20        4
Name: count, dtype: int64

In [32]:
df[df["BHK_NO."] >= 10]

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
2215,Owner,0,0,12,BHK,6373.486297,1,1,"Ashok Nagar , Kalapatti, Coimbatore District,C...",11.086274,77.033799,200.00
3466,Owner,0,0,20,BHK,348.863897,1,1,"Rat,Ratnagiri",16.983330,73.300000,15.20
3882,Owner,0,0,10,BHK,42500.000000,1,1,"Dharga,Hosur",12.720000,77.820000,0.85
8872,Dealer,0,0,13,BHK,10460.251050,1,1,"Bagalur,Bangalore",13.143933,77.667304,500.00
13440,Owner,0,0,17,BHK,11000.343760,1,1,"Karanodai,Chennai",13.252330,80.163376,320.00
13993,Dealer,0,0,10,BHK,4356.740133,1,1,"Kuansh,Bhadrak",21.069237,86.520259,85.00
16278,Owner,0,0,15,BHK,3000.107147,1,1,"Jharapada,Bhubaneswar",20.275267,85.862407,280.00
16397,Owner,0,0,11,BHK,4000.000000,1,1,"Jaipur road,Bikaner",28.863593,74.048835,55.00
16429,Owner,0,0,15,BHK,15001.153930,1,1,"Laggere,Bangalore",13.008595,77.523704,650.00
17160,Owner,1,0,12,BHK,4570.848146,0,1,"Vilankurichi,Coimbatore",11.074387,77.018510,180.00
19425,Owner,0,0,12,BHK,4824.561404,1,1,"Factory circle bashettalli,Bangalore",21.000000,77.000000,110.00
20730,Owner,0,0,10,BHK,1480.000000,1,1,"Gururaja Layout,Bangalore",12.969910,77.597960,370.00
20745,Owner,1,0,20,BHK,7000.000000,0,1,"Hunasamaranahalli,Bangalore",13.143000,77.619000,350.00
25603,Owner,0,0,15,BHK,8000.000000,1,1,"Kadri,Mangalore",12.884190,74.855260,500.00
26200,Dealer,0,0,20,BHK,11983.122360,1,1,"Ashoknagar,Udaipur",24.583330,73.683330,710.00
26233,Owner,0,0,10,BHK,7500.000000,1,1,"P&T Colony,Bangalore",16.502078,80.647557,600.00
29004,Dealer,0,0,15,BHK,5894.736842,1,1,"Kalikapur,Kolkata",22.127030,88.518729,280.00
29187,Owner,0,0,20,BHK,16860.563140,1,1,"Seethammadhara,Visakhapatnam",17.741878,83.308875,2000.00

In [33]:
df[df["BHK_NO."] >= 10][
    [
        "ADDRESS",
        "BHK_NO.",
        "SQUARE_FT",
        "TARGET(PRICE_IN_LACS)"
    ]
]

,ADDRESS,BHK_NO.,SQUARE_FT,TARGET(PRICE_IN_LACS)
2215,"Ashok Nagar , Kalapatti, Coimbatore District,C...",12,6373.486297,200.00
3466,"Rat,Ratnagiri",20,348.863897,15.20
3882,"Dharga,Hosur",10,42500.000000,0.85
8872,"Bagalur,Bangalore",13,10460.251050,500.00
13440,"Karanodai,Chennai",17,11000.343760,320.00
13993,"Kuansh,Bhadrak",10,4356.740133,85.00
16278,"Jharapada,Bhubaneswar",15,3000.107147,280.00
16397,"Jaipur road,Bikaner",11,4000.000000,55.00
16429,"Laggere,Bangalore",15,15001.153930,650.00
17160,"Vilankurichi,Coimbatore",12,4570.848146,180.00
19425,"Factory circle bashettalli,Bangalore",12,4824.561404,110.00
20730,"Gururaja Layout,Bangalore",10,1480.000000,370.00
20745,"Hunasamaranahalli,Bangalore",20,7000.000000,350.00
25603,"Kadri,Mangalore",15,8000.000000,500.00
26200,"Ashoknagar,Udaipur",20,11983.122360,710.00
26233,"P&T Colony,Bangalore",10,7500.000000,600.00
29004,"Kalikapur,Kolkata",15,5894.736842,280.00
29187,"Seethammadhara,Visakhapatnam",20,16860.563140,2000.00

In [34]:
df["SQUARE_FT"].describe()

count    2.905000e+04
mean     2.003171e+04
std      1.914411e+06
min      3.000000e+00
25%      9.000000e+02
50%      1.172742e+03
75%      1.550169e+03
max      2.545455e+08
Name: SQUARE_FT, dtype: float64

In [35]:
df[df["SQUARE_FT"] < 100]

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
2092,Owner,0,0,2,BHK,5.000000,1,1,"Sector-29 Chandigarh,Chandigarh",30.755000,76.777256,45.0
2323,Owner,0,0,2,BHK,49.800797,1,1,"Civil Lines,Nagpur",21.152819,79.069531,30.0
2981,Owner,0,0,3,BHK,99.975006,1,1,"Bhatnagar Colony,Jind",29.305611,76.323316,40.0
3269,Owner,0,0,2,BHK,3.000000,1,1,"industrial area,Hajipur",23.525713,87.287479,12.0
4774,Owner,0,0,2,BHK,98.000784,1,1,"Dodhpur,Aligarh",27.244478,77.782574,50.0
9390,Owner,0,0,1,BHK,54.999450,1,1,"Sector-17 Vasundhara,Ghaziabad",28.649273,77.355737,35.0
9825,Owner,0,0,2,BHK,74.000987,1,1,"Baina Vasco,Goa",15.395220,73.807730,39.0
10462,Owner,0,0,1,BHK,55.000000,1,1,"Govardhan,Mathura",27.494145,77.465069,16.5
10496,Owner,1,1,2,BHK,70.883870,0,1,"Sangolda,Goa",15.550351,73.805282,48.8
10716,Owner,0,0,2,BHK,91.000091,1,1,"Swarna Jayanti Nagar,Aligarh",27.892383,78.101489,30.0
11117,Owner,0,0,1,BHK,49.000092,1,1,"kakinada,Kakinada",16.979477,82.240758,16.0
12811,Owner,0,0,1,BHK,80.000000,1,1,"Nhare Pune,Pune",18.523610,73.847780,24.0
13763,Owner,0,0,2,BHK,3.985594,1,1,"Amlidih,Raipur",21.213822,81.676956,24.9
14715,Owner,0,0,1,BHK,58.001436,1,1,"Assonora,Goa",15.618700,73.898600,21.0
15020,Owner,0,0,4,BHK,45.000191,1,1,"Swarn Jayanti Vihar,Kanpur",26.472500,80.331110,23.5
15152,Owner,0,0,1,BHK,10.979906,1,1,"Ganesh Colony,Jalgaon",21.047939,75.770559,27.3
15435,Owner,0,0,1,BHK,32.000000,1,1,"Makanpur,Ghaziabad",28.636759,77.354534,13.0
17167,Owner,0,0,2,BHK,80.000000,1,1,"Kamla Nagar,Agra",27.221766,78.026673,22.0
20146,Owner,1,0,1,BHK,60.001091,0,1,"Hanspuram,Kanpur",26.472500,80.331110,22.0
20434,Builder,1,1,1,BHK,90.252708,0,0,"Roha,Maharashtra",18.454300,73.114700,2.0
20521,Owner,0,0,1,BHK,31.780067,1,1,"Parthala Khanjarpur,Noida",28.593122,77.400208,16.6
23849,Owner,0,0,1,BHK,37.680696,1,1,"Munnu Khera,Lucknow",26.823489,80.858175,16.5
24528,Owner,0,0,2,BHK,9.397110,1,1,"Brajanathchak,Haldia",22.030000,88.060000,32.5
24572,Owner,0,0,1,BHK,32.000000,1,1,"Sector-118 Noida,Noida",28.579845,77.403693,16.0
26485,Owner,0,0,1,BHK,10.000000,1,1,"Punagam,Surat",21.216630,72.899374,8.0
29308,Builder,1,1,1,BHK,90.252708,0,0,"Roha,Raigad",18.454300,73.114700,2.0

In [36]:
df[df["SQUARE_FT"] > 100000]

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
294,Builder,1,1,3,BHK,106469.0027,0,0,"Vishrantwadi,Lalitpur",24.690280,78.418890,9480.0
373,Owner,0,0,4,BHK,433333.3333,1,1,"Mulanthuruthy,Kochi",9.893479,76.408774,65.0
554,Dealer,1,1,3,BHK,113785.5580,0,0,"Dabolim,Goa",15.384909,73.850001,7280.0
722,Builder,0,0,3,BHK,134884.5664,1,0,"Deolali Camp,Maharashtra",19.908529,73.831516,7420.0
1225,Dealer,1,1,3,BHK,147428.5714,0,0,"New Chandigarh,Chandigarh",30.735280,76.791110,5160.0
...,...,...,...,...,...,...,...,...,...,...,...,...
27036,Dealer,1,1,3,BHK,174909.0909,0,0,"Sector-89 A Gurgaon,Gurgaon",28.418638,76.945416,9620.0
27998,Builder,1,0,3,BHK,154444.4444,0,0,"Vennala,Kochi",9.930471,76.271273,8340.0
28049,Builder,1,1,3,BHK,158840.4814,0,0,"KR Puram,Bangalore",13.010349,77.712151,9370.0
28591,Owner,0,0,2,BHK,875000.0000,1,1,"Ajit Singh Nagar,Vijayawada",30.466084,74.501902,35.0
29002,Builder,1,1,3,BHK,157454.5455,0,0,"8th Phase JP Nagar,Bangalore",12.905368,77.580403,8660.0